services:
  - type: web
    name: cloth-store-backend
    runtime: python
    plan: free 
    region: singapore  # Choose closest to you (singapore/mumbai)
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi --bind 0.0.0.0:$PORT
    healthCheckPath: /api/products/products/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings_prod
      - key: DATABASE_URL
        fromDatabase:
          name: cloth-store-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

databases:
  - name: cloth-store-db
    plan: free 
    databaseName: clothstore
    user: clothstore_user
    region: singapore
